# Generated by Django 3.0.8 on 2020-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=40)),
                ('premier', models.DateTimeField(max_length=4)),
                ('avg_tomatometer', models.CharField(max_length=3)),
                ('avg_audience_score', models.CharField(max_length=3)),
            ],
        ),
    ]
